### PR TITLE
Add standard Agoran Header

### PR DESCRIPTION
**Pull request by nixnull**
Looks like this when applied: https://nichdel.github.io/Registrar/

### CODE REVIEW

**Comment by nixnull** [comment]
@falsifian Pinging you on this PR in case you missed it. I don't have push rights on this repo.

**Comment by falsifian** [comment]
Thanks; I think I need to adjust my notification settings.

Can you briefly explain what is going on here? I'm confused about the existence of a file `_includes/default.html` affecting what happens when someone loads `index.html`. Is there some sort of Github preprocessing involved, and is that documented somewhere?

Do the script tags do anything? It would be nice if the site worked properly on a dumb browser with Javascript disabled, but I won't block this on that; just trying to wrap my head around this.

**Comment by falsifian** [comment]
Okay, I figured out the script tags. The navbar styles used in `header.html` are part of Bootstrap and there's some Javascript that makes a menu appear under "Archives".

I will merge, but am still curious where `_includes/default.html` behaviour is documented.

Thanks for your help.

**Comment by nixnull** [comment]
@falsifian This behavior is inherited from jekyll, and documented [here](https://jekyllrb.com/docs/themes/).

**Comment by falsifian** [comment]
Thanks! I guess now I know what to search for (Jekyll) if I have questions about how stuff in the Github repo gets translated to html etc for the website.

**Pull request merged**
